
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # HDFS direct interaction
  config.vm.network "forwarded_port", guest: 8020, host: 8020
  # HDFS direct interaction
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  # HDFS namenode web interface
  config.vm.network "forwarded_port", guest: 50070, host: 50070
  # HDFS secondary namenode web interface
  config.vm.network "forwarded_port", guest: 50090, host: 50090
  # HDFS datanode web interface
  config.vm.network "forwarded_port", guest: 50075, host: 50075
  # HDFS data transfer
  config.vm.network "forwarded_port", guest: 50010, host: 50010
  
  # YARN resource manager (application submission)
  config.vm.network "forwarded_port", guest: 8032, host: 8032
  # YARN resource manager web interface
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  # YARN node manager web interface
  config.vm.network "forwarded_port", guest: 50060, host: 50060

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.hostname = "hadoop-pseudo-yarn"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
	
	# Set the VirtualBox VM name equal to the hostname
	vb.name = config.vm.hostname.to_s

    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  # Initial run script, executed with root privileges
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    echo Updating apt repository
    apt-get update -y
    echo Installing OpenJDK 7
    apt-get install -y openjdk-7-jdk
  SHELL
  
  # Initial run script, executed as the vagrant user
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # echo Downloading Hadoop distribution
    # wget -q http://mirrors.rackhosting.com/apache/hadoop/common/hadoop-2.7.1/hadoop-2.7.1.tar.gz 
	echo Copying Hadoop distribution from the host
	cp /vagrant/hadoop-2.7.1.tar.gz ~
    tar -zxf hadoop-2.7.1.tar.gz
    chown -R vagrant hadoop-2.7.1 
    echo Overwriting hadoop-env.sh
    cat /vagrant/hadoop_conf/hadoop-env.sh > hadoop-2.7.1/etc/hadoop/hadoop-env.sh
    echo Overwriting core-site.xml
    cat /vagrant/hadoop_conf/core-site.xml > hadoop-2.7.1/etc/hadoop/core-site.xml
    echo Overwriting hdfs-site.xml
    cat /vagrant/hadoop_conf/hdfs-site.xml > hadoop-2.7.1/etc/hadoop/hdfs-site.xml
	echo Overwriting mapred-site.xml
    cat /vagrant/hadoop_conf/mapred-site.xml > hadoop-2.7.1/etc/hadoop/mapred-site.xml
	echo Overwriting yarn-site.xml
    cat /vagrant/hadoop_conf/yarn-site.xml > hadoop-2.7.1/etc/hadoop/yarn-site.xml
    echo Setting up passwordless ssh
    ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    echo StrictHostKeyChecking no >> ~/.ssh/config
    echo Formatting namenode
    hadoop-2.7.1/bin/hdfs namenode -format
  SHELL

  # Run always
  config.vm.provision "shell", privileged: false, run: "always", inline: <<-SHELL
    echo Starting DFS
    hadoop-2.7.1/sbin/start-dfs.sh
	echo Starting YARN
	hadoop-2.7.1/sbin/start-yarn.sh
  SHELL
  
  # Initial run script, executed as the vagrant user. Needs to run after starting HDFS.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo Creating /user/vagrant directory in HDFS
	hadoop-2.7.1/bin/hdfs dfs -mkdir /user
	hadoop-2.7.1/bin/hdfs dfs -mkdir /user/vagrant
	echo Loading hdfs_preloaded_data contents into /user/vagrant
	hadoop-2.7.1/bin/hdfs dfs -put /vagrant/hdfs_preloaded_data/* /user/vagrant
  SHELL
end
